name: All builds
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Install golint
        run: go get -v -u golang.org/x/lint/golint

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: golint ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          install-go: false
          version: "2021.1.2"

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v -race ./...

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build

